FUNCTIONS
```{r}
length(linkedin)
head(linkedin,2)
tail(linkedin,2)

help("length")
?length
```

USE A FUNCTION
```{r}
avg_li <- mean(linkedin)
avg_li
sum(linkedin)
abs(linkedin)
```
WRITE A FUNCTION
```{r}
pow_two <- function(arg){
  arg**2
}

pow_two(2)

sum_abs <- function(arg1, arg2){
  abs(arg1) + abs(arg2)
}

sum_abs(-2, 3)

hello <- function(){
  print("Hi there!")
  return(TRUE)
}

hello()

pow_two <- function(x, print_info = TRUE){
  y <- x^2
  if(print_info){
    print(paste(x, "to the power two equals", y))
  }
  return(y)
}

pow_two(3,FALSE)

interpret <- function(num_views){
  if(num_views > 15){
    print("Youre popular")
    return(num_views)
  } else{
    print("try to be more visible")
    return(0)
  }
}

interpret(linkedin[2])

interpret_all <- function(views, return_sun = TRUE){
  count <- 0
  for (v in views) {
    count <- count + interpret(v)
  }
  
  if(return_sun){
    return(count)
  } else{
    return(NULL)
  }
}

interpret_all(linkedin)

```
```{r}
install.packages("ggplot2")
```

```{r}
library(ggplot2)

mtcars

qplot(mtcars$wt, mtcars$hp)
```

THE APPLY FAMILY

lappy
```{r}

pioneers <- c("Gaus:17777", "Bayes:1702", "Pascal:1623", "Pearson:1857")

split_math <- strsplit(pioneers, split = ":")

split_low <- lapply(split_math, tolower)

select_first <- function(x){
  x[2]
}

names <- lapply(split_low, select_first)

years <- lapply(split_low, select_first)

```
LAPPLY AND ANONYMOUS FUNCTIONS
```{r}

split_low
names <- lapply(split_low, function(x){x[1]})
years <- lapply(split_low, function(x){x[2]})

```
USE APPLY WITH ADDITIONAL ARGUMENTS

```{r}

select_el <- function(x, index){
  x[index]
}

select_el(split_low, 1)

names <- lapply(split_low, select_el, 1)
years <- lapply(split_low, select_el, 2)

```
sapply
```{r}
names <- sapply(split_low, select_el, 1)


extreme_avg <- function(x){
  (min(x)+max(x))/2
}

vec1 <- c(3,4,5,78)
vec2 <- c(8,8,4,1)
vec3 <- c(7,8,9,5)
temp <- list(vec1, vec2, vec3)

sapply(temp, extreme_avg)
```

vapply
```{r}

basic <- function(x){
  c(min = min(x), mean = mean(x), max = max(x))
}

vapply(temp, basic, numeric(3)) #solo datos tipo numeric y longitud de 3 (este parámetro puede cambiar)

```
MATH UTILITIES
```{r}

errors <- c(1.9,-2.6,4.0,-9.5,-3.4,7.3)
print(sum(abs(errors)))

```

