EQUALITY
```{r}
"Rchitec" != "rchitec"
TRUE == FALSE 
-6 * 14 != 17 - 101
TRUE == 1

-6 * 5 + 2 >= 10 + 1
"raining" <= "raining dogs" #compara la cantidad de caracteres 
TRUE < FALSE 
```

COMPARE VECTORS

```{r}
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
facebook <- c(17, 9, 16, 5, 2, 13, 14)

linkedin > 15
facebook <= 5

linkedin > facebook
```

COMPARE MATRICES

```{r}
views <- matrix(c(linkedin,facebook), nrow = 2, byrow = TRUE)
views

views == 13
views <= 14
```
& AND |
```{r}
linkedin
last <- tail(linkedin,1)

last > 5 | last < 10
last > 15 & last <= 20

linkedin > 10 & facebook < 10
linkedin >= 12 | facebook >= 12
```
CONDITIONAL IF
```{r}

medium <- "Facebook"
num_views <- 14

if(medium == "Linked"){
  print("Showing Linkedin information")
}else if(medium == "Facebook"){
  print("Showing Facebook information")
}else{
  print("unknown medium")
}

if(num_views > 15){
  print("You are popular")
}else if(num_views <= 15 & num_views > 10){
  print("Your number of views is average")
}else{
  print("Try to be more visible")
}

```

```{r}
result <- ""
number <- 6

if(number < 10){
  if(number < 5){
    result <- "extra small"
  }
  else {
    result <- "small"
  }
}else if(number < 100){
  result <- "medium"
}else {
  result <- "large"
}

print(result)
```
WHILE
```{r}

speed <- 64

while (speed > 30) {
  print("slow down!")
  speed <- speed - 7
}
speed
```
```{r}

while (speed > 30) {
  print(paste("your speed is ",speed))
  if(speed >= 48){
    print("Slow down big time!")
    speed <- speed - 11
  }else{
    print("Slow down!")
    speed <- speed - 6
  }
}
```
STOP WHILE: BREAK

```{r}
speed <- 75

while (speed > 30) {
  print(paste("your speed is ", speed))
  
  if(speed > 80){
    break
  }
  
  if(speed > 48){
    print("slow down big time!")
    speed <- speed - 11
  }else {
    print("slown down!")
    speed <- speed - 6
  }
}

```
BUILD A WHLE LOOOP FROM SCRATCH
```{r}
i <- 1

while (i<=10) {
  print(3*i)
  
  if((i*3) %% 8 == 0){
    break
  }
  i <- i + 1
}
```
LOOP OVER A VECTOR

```{r}
linkedin <- c(16,9,13,5,2,17,14)

for(l in linkedin){
  print(l)
}

for (i in 1:length(linkedin)) { #rango que va desde la posición 1 hasta la longitud del vector
  print(linkedin[i])
}

```
LOOP OVER A LIST

```{r}
nyc <- list(pop = 840698, boroughs <- c("Manhatan","Bronx","Brooklyn","Queens","Staten Island"), capital=FALSE)

for (n in nyc) {
  print(n)
}

for (i in 1:length(nyc)) {
  print(nyc[[i]])
}
```
LOOP OVER A MATRIX
```{r}
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

box_office <- c(new_hope, empire_strikes, return_jedi)
box_office

stars_wars_matrix <- matrix(box_office, byrow = TRUE, nrow=3)
stars_wars_matrix

for (i in 1:nrow(stars_wars_matrix)) {
  for (j in 1:ncol(stars_wars_matrix)) {
    print(paste("on row", i, "and column", j ,"the board contains", stars_wars_matrix[i,j]))
  }
}

```
```{r}

for (li in linkedin) {
  if(li > 10){
    print("You're popular")
  }
  else{
    print("Be more visible")
  }
  if(li > 16){
    print("This is ridiculous")
    break
  }
  if(li > 5){
    print("this is to embarrassing")
  }
  print(li)
}
```

