ARITHMETIC WITH R

```{r}
5 + 5 - 3
28-3
5*5
(5+5)/2
28%%6


```

VARIABLE ASSIGMENT

```{r}
x = 10
x
x <- 15

y <- 9

x+y
result <- x-y
result
```

BASIC DATA TYPES IN R

```{r}
my_numeric <- 423

my_character <- "universe"

my_logical <- FALSE

class(my_numeric) #comentario 
class(my_character)
class(my_logical)
```

VECTORS

```{r}

numeric_vector <- c(1,4,10)
numeric_vector

character_vector <- c("a", "b", "c")

boolean_vector <- c(TRUE, FALSE, TRUE)

character_vector
boolean_vector

poker_vector <- c(140, -50, -20, -120, 240)
roulette_vector <- c(-24, -50, 10, 350, 10)


```

NAMING A VECTOR


```{r}

names(poker_vector) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
poker_vector

days <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

names(roulette_vector) <- days
roulette_vector

```

SELECTION BY COMPARISION 

```{r}

age <- 17
age >= 18

selection_vector <- poker_vector > 0 #compara cada valor del vector con el no. indicado
selection_vector

poker_winning_days <- poker_vector[selection_vector] #muestra unicamente los datos que cumplen con la condicion 
poker_winning_days


```

CALCULATING

```{r}

x_vector <- c(1,2,3)
y_vector <- c(4,5,6)

result_vector <- y_vector + x_vector
result_vector
```

VECTOR SELECTION
```{r}
poker_vector
poker_vector[3]
poker_vector[c(2,3,4)] #se crea una colección interna de los datos a consultar
poker_vector[2:5]
```
MATRICES
```{r}

matrix(1:9, byrow = TRUE, nrow = 3)
```
ANALYZE MATRICES
```{r}

new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

box_office <- c(new_hope, empire_strikes, return_jedi)
box_office

stars_wars_matrix <- matrix(box_office, byrow = TRUE, nrow=3)
stars_wars_matrix
```
NAMING MATRICES
```{r}

region <- c("us", "non-us")
titles <- c("A new hope", "The empire strikes back", "Return of the Jedi")

colnames(stars_wars_matrix) <- region
rownames(stars_wars_matrix) <- titles
stars_wars_matrix

```
rowsums
```{r}
rowSums(stars_wars_matrix)
colSums(stars_wars_matrix)
```
CBIND & RBIND
```{r}
total1 <- rowSums(stars_wars_matrix)
total2 <-colSums(stars_wars_matrix)

total <- cbind(stars_wars_matrix, total1)
total <- rbind(total, total2)
total
```
SELECTION OF MATRIX ELEMENTS
```{r}
stars_wars_matrix[1,2]
stars_wars_matrix[1:2,2]
stars_wars_matrix[c(1,3),1]
stars_wars_matrix[c(1,3),]
```
ARITHMETIC
```{r}

mean <- stars_wars_matrix/5
mean*2
```
FACTOR
```{r}
sex_vector <- c("male", "female", "female", "male", "male")
factor_sex_vector <- factor(sex_vector)
factor_sex_vector
```
```{r}
temperature_vector <- c("High","Low","High","Low","Medium")
factor_temperature_vector <- factor(temperature_vector, order = TRUE,levels = c("Low","Medium","High"))
factor_temperature_vector
```
FACTOR LEVELS
```{r}
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)
factor_survey_vector
levels(factor_survey_vector) <- c("Female", "Male")
```
SUMMARY
```{r}
summary(factor_survey_vector)
```
ORDERED FACTORS
```{r}
male <- factor_survey_vector[1]
female <- factor_survey_vector[2]

male > female

speed_vector <- c("Medium", "Slow", "Slow", "Medium", "Fast")
factor_speed_vector <- factor(speed_vector)
factor_speed_vector <- factor(speed_vector, ordered = TRUE, levels = c("Slow", "Medium", "Fast"))
factor_speed_vector

speed_1 <- factor_speed_vector[2]
speed_5 <- factor_speed_vector[5]

speed_1 > speed_5
```

