GROUPING AND SUMMARIZING
Summarizing the median life expentancy
```{r}
gapminder %>%
  summarise(medianLifeExp = median(lifeExp))

#Filter for 1957 then summarize the median life expectancy

gapminder %>%
  filter(year == 1957) %>%
  summarise(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))

```

SUMMARIZING BY YEAR
```{r}

gapminder %>%
  group_by(year) %>% #a cada año agrupado le aplica las funciones a continuación 
  summarise(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))

```

SUMMARIZING BY CONTINENT
```{r}

gapminder %>%
  filter(year == 1957) %>%
  group_by(continent) %>%
  summarise(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap)) %>%
  arrange(desc(maxGdpPercap))

```

SUMMARIZING BY CONTINENT AND YEAR
```{r}
gapminder %>%
  group_by(continent, year) %>%
  summarise(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap)) 
```
LINE PLOTS

VISUALIZING MEDIAN LIFE EXPECTANCY OVER TIME

```{r}
by_year <- gapminder %>%
  group_by(year) %>%
  summarise(medianGdpPercap = median(gdpPercap))

ggplot(by_year, aes(x = year, y = medianGdpPercap)) +
  geom_line()

```

```{r}
by_year_continent <- gapminder %>%
  group_by(year, continent) %>%
  summarise(medianGdpPercap = median(gdpPercap))

ggplot(by_year_continent, aes(x = year, y = medianGdpPercap, color = continent)) +
  geom_line()

```

BAR PLOTS

VISUALIZING MEDIAN GDP PER CAPITA BY CONTINENT

```{r}

by_continent <- gapminder %>%
  filter(year == 1952) %>%
  group_by(continent) %>%
  summarise(medianGdpPercap = median(gdpPercap))

  
ggplot(by_continent, aes(x=continent, y = medianGdpPercap)) +
  geom_col()


```


```{r}

oceania_1952 <- gapminder %>%
  filter(continent == "Oceania", year == 1952)

ggplot(oceania_1952, aes(x=country, y = gdpPercap))+
  geom_col()


```

